version: '3.8'
services:
  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - 4317:4317
    restart: always
    environment:
      - INFLUXDB_URL=http://host.docker.internal:8086
      - INFLUXDB_TOKEN=w58r-LpM-fCcyvfDC9XDtGATn-Yyz0WJUpMuJqVQ73SS6k4czPCOsvSq3uKGTP1kTXEYc9ehQ6-o9beoXADlIg==
    extra_hosts:
      - "host.docker.internal:host-gateway"

